# Generated by Django 5.1.3 on 2024-11-30 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libApp', '0004_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='level',
            new_name='levels',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='name',
            new_name='names',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='phone',
            new_name='phoneNumber',
        ),
    ]
