# Generated by Django 5.1.3 on 2024-12-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libApp', '0005_rename_level_members_levels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('regNo', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('dateJoined', models.DateTimeField(auto_now_add=True)),
                ('levels', models.CharField(max_length=100)),
                ('bkBorrowed', models.CharField(max_length=100)),
                ('dueDate', models.DateTimeField()),
            ],
        ),
    ]
