# Generated by Django 5.1.3 on 2024-12-01 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libApp', '0006_borrowers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Borrowers',
            new_name='BorrowersList',
        ),
    ]
