# Generated by Django 5.1.3 on 2024-12-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libApp', '0007_rename_borrowers_borrowerslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Librarian', 'Librarian'), ('Student', 'Student')], default='Student', max_length=20),
        ),
    ]
